name: Build & Test Grocery App

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # -------- Restore dependencies --------
      - name: Restore solution
        run: dotnet restore Grocery.sln

      # -------- Build & Run Unit Tests --------
      - name: Build for Tests
        run: dotnet build Grocery.sln --no-restore --configuration Release

      - name: Run Unit Tests
        run: dotnet test TestCore/TestCore.csproj --no-build --configuration Release --logger "trx;LogFileName=test_results.trx" --results-directory ./TestResults

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: ./TestResults

      # -------- Build MAUI Windows --------
      - name: Build MAUI Windows
        if: success()  # only if tests passed
        run: dotnet publish Grocery.App/Grocery.App.csproj -c Release -f net8.0-windows10.0.19041.0 -r win-x64 -p:PublishReadyToRun=false --self-contained true -o ./artifacts/windows

      - name: Upload Windows Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: GroceryApp-Windows
          path: ./artifacts/windows

      # -------- Build MAUI Android --------
      - name: Build MAUI Android
        if: success()  # only if tests passed
        run: dotnet publish Grocery.App/Grocery.App.csproj -c Release -f net8.0-android -p:AndroidPackageFormat=apk -o ./artifacts/android

      - name: Upload Android Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: GroceryApp-Android
          path: ./artifacts/android
